const UPDATE_PROJECT = 'UPDATE_PROJECT';
const UPDATE_STORE = 'UPDATE_STORE';
const INITIALIZE_MAP = 'INITIALIZE_MAP';
const TOGGLE_GROUP = 'TOGGLE_GROUP';
const TOGGLE_ITEM = 'TOGGLE_ITEM';
const SELECT_ITEM = 'SELECT_ITEM';
const CHANGE_OPACITY = 'CHANGE_OPACITY';
const CROP = 'CROP';
const ZOOM_TO_LAYER = 'ZOOM_TO_LAYER';
const UPDATE_MASK = 'UPDATE_MASK';
const ADD_RESOURCE = 'ADD_RESOURCE';
const REMOVE_RESOURCE = 'REMOVE_RESOURCE';

module.exports = {
  UPDATE_PROJECT,
  UPDATE_STORE,
  INITIALIZE_MAP,
  TOGGLE_GROUP,
  TOGGLE_ITEM,
  SELECT_ITEM,
  CHANGE_OPACITY,
  CROP,
  ZOOM_TO_LAYER,
  UPDATE_MASK,
  ADD_RESOURCE,
  REMOVE_RESOURCE,
};
